# Telegram Bot Configuration
telegram:
  bot_token: "YOUR_BOT_TOKEN_HERE"  # Get from @BotFather on Telegram

# Game Configuration
game:
  name: "AmazingRaceBot"
  max_teams: 10
  max_team_size: 5
  
  # Location-based verification settings
  # When enabled, teams must be within the specified radius of a challenge's 
  # location coordinates to unlock the next challenge (starting from challenge 2)
  location_verification_enabled: false  # Set to true to enable location verification
  
  # Challenge definitions
  # Note: Challenges are completed sequentially - teams must complete
  # challenge 1 before they can attempt challenge 2, and so on.
  # 
  # Challenge Types:
  # - photo: Teams submit photos (e.g., team photo at location, completed puzzle)
  # - riddle: Teams solve riddles/puzzles and submit text answer
  # - code: Teams write/debug code and submit solution
  # - qr: Teams find and scan QR codes (auto-verified)
  # - trivia: Teams answer trivia questions
  # - location: Teams visit specific GPS locations
  # - text: General text submission challenge
  # - scavenger: Teams find and document items (via photos)
  # - team_activity: Teams perform activities (verified by photo/video)
  # - decryption: Teams decrypt encoded messages
  #
  # Verification Methods:
  # - answer: Text answer that must match (case-insensitive, trimmed)
  # - photo: Requires photo submission (manual admin verification)
  # - location: GPS coordinates verification (latitude, longitude, radius in meters)
  # - auto: Automatically verified (e.g., QR code scan)
  challenges:
    - id: 1
      name: "Find the Landmark"
      description: "Take a team photo with the city skyline in the background"
      location: "Downtown Viewpoint"
      type: "photo"
      verification:
        method: "photo"
      # Optional: GPS coordinates for location-based verification (latitude, longitude)
      # Location verification is skipped for challenge 1 (starting point)
      coordinates:
        latitude: 37.7749
        longitude: -122.4194
        radius: 100  # Verification radius in meters (default: 100m)
      # Optional: Hints (up to 3 hints per challenge)
      # Each hint costs 2 minutes penalty when the next challenge is unlocked
      hints:
        - "Look for the tallest building in the area"
        - "The viewpoint is near the waterfront"
        - "Check the tourist information center for directions"
      # Optional: Custom success message shown after completing the challenge
      # This message is sent in addition to the standard completion confirmation
      success_message: "🎉 Great job finding the landmark! Head to the library for your next challenge."
      
    - id: 2
      name: "Riddle Master"
      description: "I stand tall where knowledge flows, students gather in my shadow's throes. What am I?"
      location: "Campus"
      type: "riddle"
      verification:
        method: "answer"
        answer: "library"
      coordinates:
        latitude: 37.7849
        longitude: -122.4094
        radius: 100
      hints:
        - "Think about where students study"
        - "It's a building full of books"
      success_message: "🧩 Excellent! The library it is. Your next challenge involves some coding skills!"
      
    - id: 3
      name: "Code Debug"
      description: "Fix this function to correctly calculate Fibonacci numbers. Submit the corrected function."
      location: "Lab A"
      type: "code"
      verification:
        method: "answer"
        answer: "fibonacci"  # Keyword to check in submission
      coordinates:
        latitude: 37.7949
        longitude: -122.3994
        radius: 100
      
    - id: 4
      name: "QR Hunt"
      description: "Find the QR code hidden near the water fountain"
      location: "Main Courtyard"
      type: "qr"
      verification:
        method: "answer"
        answer: "FOUNTAIN_2024"  # QR code contains this text
      coordinates:
        latitude: 37.8049
        longitude: -122.3894
        radius: 100
      
    - id: 5
      name: "Tech Trivia"
      description: "Name three inventors who contributed to the development of the modern computer (comma-separated)"
      location: "Anywhere"
      type: "trivia"
      verification:
        method: "answer"
        answer: "turing, lovelace, babbage"  # Accept if contains these names
      # No coordinates needed - can be completed anywhere
      
    - id: 6
      name: "Team Pyramid"
      description: "Create a human pyramid with your team"
      location: "Outdoor Area"
      type: "team_activity"
      verification:
        method: "photo"
      coordinates:
        latitude: 37.8149
        longitude: -122.3794
        radius: 100
      
    - id: 7
      name: "Scavenger Hunt"
      description: "Find and photograph 5 different types of transportation in the area"
      location: "Campus Area"
      type: "scavenger"
      verification:
        method: "photo"
      coordinates:
        latitude: 37.8249
        longitude: -122.3694
        radius: 100
      
    - id: 8
      name: "Secret Message"
      description: "Decode this Caesar cipher (shift 3): Frqjudwxodwlrqv"
      location: "Anywhere"
      type: "decryption"
      verification:
        method: "answer"
        answer: "congratulations"
      # No coordinates needed - can be completed anywhere

# Admin user (Telegram user ID)
# Note: Only one admin is allowed
admin: 123456789  # Replace with actual admin user ID
