# Telegram Bot Configuration
telegram:
  bot_token: "YOUR_BOT_TOKEN_HERE"  # Get from @BotFather on Telegram

# Game Configuration
game:
  name: "uCode Amazing Race"
  max_teams: 10
  max_team_size: 5
  
  # Challenge definitions
  # Note: Challenges are completed sequentially - teams must complete
  # challenge 1 before they can attempt challenge 2, and so on.
  challenges:
    - id: 1
      name: "First Challenge"
      description: "Find the hidden clue in the main hall"
      location: "Main Hall"
      
    - id: 2
      name: "Code Puzzle"
      description: "Solve the programming puzzle"
      location: "Lab A"
      
    - id: 3
      name: "Team Challenge"
      description: "Complete the team building activity"
      location: "Outdoor Area"
      
    - id: 4
      name: "Final Sprint"
      description: "Race to the finish line"
      location: "Starting Point"

# Admin users (Telegram user IDs)
admins:
  - 123456789  # Replace with actual admin user IDs
